<a href="https://colab.research.google.com/github/harshadhande/First_Repo/blob/main/Numpy__basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Importing Numpy**

In [ ]:
import numpy as np

#**Create numpy**

In [ ]:
a=np.array([1, 2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 2d and 3d
b=np.array([[1, 2,3], [ 4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:

c=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#dtype
np.array([1, 2,3], dtype=float)

array([1., 2., 3.])

In [ ]:
a = np.array([1, 2, 3], dtype=np.uint8)
print(a)
print(a.dtype)
b = np.array([1, 2, 3], dtype=complex)
print(b)
print(b.dtype)

[1 2 3]
uint8
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
a=np.arange(0, 10,3)
a

array([0, 3, 6, 9])

In [ ]:
 #with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# np.ones and np.zeros
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3, 4))

array([[0.70826685, 0.65842891, 0.08362838, 0.87444377],
       [0.57996447, 0.62374924, 0.05670114, 0.08434905],
       [0.34541348, 0.73045686, 0.16641962, 0.08871152]])

In [ ]:

# np
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(-10, 10,10,dtype=float)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.random.randint(2,10,5)

array([9, 3, 7, 4, 8])

#***ATTRIBUTES OF ARRAY***

2 DIMENSION

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.ndim


[[1 2 3]
 [4 5 6]]


2

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.size

[[1 2 3]
 [4 5 6]]


6

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.dtype

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.itemsize

[[1 2 3]
 [4 5 6]]


8

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.nbytes

[[1 2 3]
 [4 5 6]]


48

1 DIMENSION

In [ ]:
a=np.array([1, 2,3,4,5,6])
a.ndim

1

In [ ]:
a.shape

(6,)

In [ ]:
a.size

6

In [ ]:
a.itemsize

8

In [ ]:
a.nbytes

48

In [ ]:
a.dtype

dtype('int64')

3 DIMENSION

In [ ]:
c=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
c.ndim

3

In [ ]:
c.shape

(2, 2, 2)

In [ ]:
c.size

8

In [ ]:
c.dtype

dtype('int64')

In [ ]:
c.itemsize

8

In [ ]:
c.nbytes

64

#**Changing Datatypes**

In [ ]:
a.astype(np.int32)

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [ ]:
a.astype(np.float32).dtype

dtype('float32')

#**Array Operations**

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
#relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

#array functions


In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[91., 46., 84.],
       [31., 68., 33.],
       [70., 34., 88.]])

In [ ]:
np.prod(a1,axis=0)

array([197470., 106352., 243936.])

In [ ]:
np.var(a1,axis=1)

array([390.88888889, 288.66666667, 504.        ])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.10598751,  0.90178835,  0.73319032],
       [-0.40403765, -0.89792768,  0.99991186],
       [ 0.77389068,  0.52908269,  0.0353983 ]])

In [ ]:
import numpy as np
c=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#log and exponents
import numpy as np

np.exp(c)

array([[[2.71828183e+00, 7.38905610e+00],
        [2.00855369e+01, 5.45981500e+01]],

       [[1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03]]])

#indexing and slicing


In [ ]:
 a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2[2:5:2]

array([[ 8.,  9., 10., 11.]])

In [ ]:
a2[0:2,1::2]

array([[1., 3.],
       [5., 7.]])

In [ ]:
a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,1:,1:]

array([[7]])